#!/usr/bin/sh

echo
echo ---------- Project directory ----------
projroot=$(cd "$(dirname "$0")"; pwd)
echo $projroot

### refresh man/*.Rd using roxygen2
echo
echo ---------- Refreshing manuals ----------
R -q -e "setwd('$projroot'); source('data-raw/example_data.R'); library(roxygen2); roxygenize()"

### build
echo
echo ---------- R CMD build ----------
time R CMD build --keep-empty-dirs --no-resave-data $projroot

echo
echo ---------- R CMD check ----------
version=`awk -F ": " '/Version/{print $2}' $projroot/DESCRIPTION`
time R CMD check iteremoval_${version}.tar.gz

echo
echo ---------- R CMD BiocCheck ----------
time R CMD BiocCheck iteremoval_${version}.tar.gz
